<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.17">
  <compounddef id="classcv__bridge_1_1core_1_1_cv_bridge_error" kind="class" language="Python" prot="public">
    <compoundname>cv_bridge::core::CvBridgeError</compoundname>
    <basecompoundref prot="public" virt="non-virtual">TypeError</basecompoundref>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
<para><verbatim>This is the error raised by :class:`cv_bridge.CvBridge` methods when they fail.
</verbatim> </para>
    </detaileddescription>
    <inheritancegraph>
      <node id="1">
        <label>cv_bridge.core.CvBridgeError</label>
        <link refid="classcv__bridge_1_1core_1_1_cv_bridge_error"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2">
        <label>TypeError</label>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="1">
        <label>cv_bridge.core.CvBridgeError</label>
        <link refid="classcv__bridge_1_1core_1_1_cv_bridge_error"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2">
        <label>TypeError</label>
      </node>
    </collaborationgraph>
    <location file="robocluedo_dependencies/vision_opencv/cv_bridge/python/cv_bridge/core.py" line="38" column="1" bodyfile="robocluedo_dependencies/vision_opencv/cv_bridge/python/cv_bridge/core.py" bodystart="38" bodyend="45"/>
    <listofallmembers>
    </listofallmembers>
  </compounddef>
</doxygen>
